# Generated by Django 5.1 on 2024-08-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_text',
            new_name='quote',
        ),
    ]
