# Generated by Django 5.1 on 2024-08-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_quote_text_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
